a couple of changes to tags.json
SkyblockClient/Website pull request #38
Opened 2023-09-19 18:29 UTC by Vahvl

added a [:3] tag to myself

Rayless asked for some things so here they are:
   included tags [GOAT] with the cool colour scheme in the pr for bobert89 and gamingmice
   removed the [cool] tag from billdepzai

message link to what rayless said cuz idk: https://discord.com/channels/780181693100982273/887818760126345246/1153743510701342810

2023-09-19 19:13 UTC, MicrocontrollersDev commented
i would like to veto this

2023-09-19 20:39 UTC, nacrt commented
i don't know what veto means but i agree with micro

2023-09-20 01:21 UTC, KTibow commented
@nacrt @MicrocontrollersDev i will be merging this pr in 12 hours if you do not leave a "request changes" review

2023-09-20 03:53 UTC, Vahvl commented
wait dont do 12h I appareantly did an oopsie with one of the UUIDs

2023-09-20 03:57 UTC, MicrocontrollersDev requested changes

2023-09-20 03:57 UTC, MicrocontrollersDev commented on docs/assets/tags.json
> +    "Vahvl": ["&5[:3]&r", "&5[:3]&r"]
delete this. completely nuke it. level the whole repository.

2023-09-20 04:08 UTC, Vahvl commented
insert crying spongebob

2023-09-20 04:10 UTC, Vahvl commented
also you can do 12h the oopsie i appareantly made is not real

2023-09-20 18:01 UTC, MicrocontrollersDev commented
> kti it has been 16h

"if you do not leave a "request changes" review"

2023-09-20 18:09 UTC, Vahvl commented
good point, however, i disagree with your opinion

2023-09-20 18:10 UTC, Vahvl commented
your [anime girl enthusiast] tag having ass can not be out here complaining abt [:3]

2023-09-20 18:10 UTC, MicrocontrollersDev commented
i forgot i had that ngl. regardless it is satirical. meanwhile yours is a warcrime

2023-09-20 18:44 UTC, Vahvl commented
is that really true man

2023-09-20 18:50 UTC, MicrocontrollersDev commented
yes that was a bit i was really committed too back then. idk how long you’ve known me but i have very clear eras where for a few months i’ll go all in for a bit and i stick with it. take the 2-3 months of keqing for example

2023-09-24 13:46 UTC, Zetvue commented
i agree with this. :3 tag

2023-09-24 13:46 UTC, Vahvl commented
very based

2023-09-24 15:31 UTC, RayDeeUx commented
proposal: merge this pull request and deny future pull requests of this nature

2023-09-24 15:32 UTC, MicrocontrollersDev commented
> proposal: merge this pull request and deny future pull requests of this nature

shut up ery

2024-01-15 22:35 UTC, KTibow commented
since consensus wasn't reached and this has gone stale i'm closing this. feel free to make another pr though.

2024-01-15 22:35 UTC, closed without merging